/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitor Stream */
        get: operations["monitor_stream_api_monitor_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Submit Job */
        post: operations["submit_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /** Patch Job */
        patch: operations["patch_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/arenas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Arenas */
        get: operations["list_arenas_api_arenas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arenas/{arena}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Arena */
        get: operations["get_arena_api_arenas__arena__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arenas/{arena}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arena Pause */
        post: operations["arena_pause_api_arenas__arena__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arenas/{arena}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arena Resume */
        post: operations["arena_resume_api_arenas__arena__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arenas/{arena}/reclaim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arena Reclaim */
        post: operations["arena_reclaim_api_arenas__arena__reclaim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arenas/{arena}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arena Cancel */
        post: operations["arena_cancel_api_arenas__arena__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/reclaim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reclaim Job */
        post: operations["reclaim_job_api_jobs__job_id__reclaim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/instances/{instance_id}/reclaim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reclaim Instance */
        post: operations["reclaim_instance_api_jobs__job_id__instances__instance_id__reclaim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry-done-err": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Done Err */
        post: operations["retry_done_err_api_jobs__job_id__retry_done_err_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Job Ep */
        post: operations["archive_job_ep_api_jobs__job_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Job Ep */
        post: operations["unarchive_job_ep_api_jobs__job_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/filter-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filter Presets */
        get: operations["get_filter_presets_api_filter_presets_get"];
        /**
         * Put Filter Presets
         * @description Opaque UI blob; whole-document last-write-wins. Atomic
         *     write so a crash can't corrupt it.
         */
        put: operations["put_filter_presets_api_filter_presets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchivePatch */
        ArchivePatch: {
            /** Auto After Days */
            auto_after_days?: number | null;
            /** Scan Interval Seconds */
            scan_interval_seconds?: number | null;
        };
        /** ArchiveSettings */
        ArchiveSettings: {
            /**
             * Auto After Days
             * @default 0
             */
            auto_after_days: number;
            /**
             * Scan Interval Seconds
             * @default 3600
             */
            scan_interval_seconds: number;
        };
        /** ArenaDetailOut */
        ArenaDetailOut: {
            /** Arena */
            arena: string;
            /** Jobs */
            jobs: number;
            /** Paused Jobs */
            paused_jobs: number;
            /** Archived Jobs */
            archived_jobs: number;
            counts: components["schemas"]["JobCountsOut"];
            /** Members */
            members: components["schemas"]["JobSummaryOut"][];
        };
        /**
         * ArenaSummaryOut
         * @description One derived group row: an arena exists iff a job names it,
         *     so there is nothing to create or delete — only to read.
         */
        ArenaSummaryOut: {
            /** Arena */
            arena: string;
            /** Jobs */
            jobs: number;
            /** Paused Jobs */
            paused_jobs: number;
            /** Archived Jobs */
            archived_jobs: number;
            counts: components["schemas"]["JobCountsOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** HostAutotunePatch */
        HostAutotunePatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Seconds Between Ticks */
            seconds_between_ticks?: number | null;
            /** Ring Buffer Size */
            ring_buffer_size?: number | null;
            /** Bootstrap Min Samples */
            bootstrap_min_samples?: number | null;
            /** Peak Floor Bytes */
            peak_floor_bytes?: number | null;
            /** Reserve Fraction */
            reserve_fraction?: number | null;
        };
        /** HostAutotuneSettings */
        HostAutotuneSettings: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Seconds Between Ticks
             * @default 60
             */
            seconds_between_ticks: number;
            /**
             * Ring Buffer Size
             * @default 50
             */
            ring_buffer_size: number;
            /**
             * Bootstrap Min Samples
             * @default 8
             */
            bootstrap_min_samples: number;
            /**
             * Peak Floor Bytes
             * @default 1073741824
             */
            peak_floor_bytes: number;
            /**
             * Reserve Fraction
             * @default 0.15
             */
            reserve_fraction: number;
        };
        /**
         * HostSettings
         * @description Per-host scheduling settings.
         *
         *     `active` is operator intent (set via PATCH /settings); `alive`
         *     is an infrastructure fact auto-flipped by the docker-events
         *     stream. Dispatch requires both.
         */
        HostSettings: {
            /** Max Concurrent */
            max_concurrent: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Alive
             * @default true
             */
            alive: boolean;
        };
        /** HostSettingsPatch */
        HostSettingsPatch: {
            /** Max Concurrent */
            max_concurrent?: number | null;
            /** Active */
            active?: boolean | null;
            /** Alive */
            alive?: boolean | null;
        };
        /** JobCountsOut */
        JobCountsOut: {
            /** Pending */
            pending: number;
            /** Running */
            running: number;
            /** Done Ok */
            done_ok: number;
            /** Done Err */
            done_err: number;
            /** Ghosted */
            ghosted: number;
            /** Unknown */
            unknown: number;
            /** Total */
            total: number;
        };
        /** JobSummaryOut */
        JobSummaryOut: {
            /** Job Id */
            job_id: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Max Concurrent */
            max_concurrent: number | null;
            /** Pause On Error */
            pause_on_error: boolean | null;
            /** Paused */
            paused: boolean;
            counts: components["schemas"]["JobCountsOut"];
            /** Home Root */
            home_root: string;
            /** Alias */
            alias: string;
            /**
             * Arena
             * @default
             */
            arena: string;
            /**
             * Pool
             * @default default
             */
            pool: string;
            /**
             * Image Id
             * @default
             */
            image_id: string;
            /**
             * Source Sha256
             * @default
             */
            source_sha256: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Archive Kind
             * @default
             */
            archive_kind: string;
        };
        /** NotifyPatch */
        NotifyPatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Thresholds */
            thresholds?: number[] | null;
            /** Telegram Chat Id */
            telegram_chat_id?: string | null;
        };
        /**
         * NotifySettings
         * @description Live-patchable; the manager re-reads every field per event.
         */
        NotifySettings: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Thresholds */
            thresholds?: number[];
            /**
             * Telegram Chat Id
             * @default
             */
            telegram_chat_id: string;
        };
        /** OrphanGCPatch */
        OrphanGCPatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Seconds Between Sweeps */
            seconds_between_sweeps?: number | null;
            /** Min Container Age S */
            min_container_age_s?: number | null;
        };
        /** OrphanGCSettings */
        OrphanGCSettings: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Seconds Between Sweeps
             * @default 30
             */
            seconds_between_sweeps: number;
            /**
             * Min Container Age S
             * @default 90
             */
            min_container_age_s: number;
        };
        /**
         * RetryDoneErrRequest
         * @description Empty body = retry every done_err instance. `instance_ids`
         *     overrides the host/since filters.
         */
        RetryDoneErrRequest: {
            /** Host */
            host?: string | null;
            /** Since Iso */
            since_iso?: string | null;
            /** Instance Ids */
            instance_ids?: string[] | null;
        };
        /** Settings */
        Settings: {
            /** Max Concurrent */
            max_concurrent: number;
            /** Hosts */
            hosts: {
                [key: string]: components["schemas"]["HostSettings"];
            };
            /**
             * Require Source
             * @default false
             */
            require_source: boolean;
            /** Pool Caps */
            pool_caps?: {
                [key: string]: number;
            };
            state_reconciliation?: components["schemas"]["StateReconciliationSettings"];
            orphan_gc?: components["schemas"]["OrphanGCSettings"];
            host_autotune?: components["schemas"]["HostAutotuneSettings"];
            notify?: components["schemas"]["NotifySettings"];
            archive?: components["schemas"]["ArchiveSettings"];
        };
        /**
         * SettingsPatch
         * @description Partial update; unknown fields are rejected, not dropped —
         *     a typo'd knob must 422, not silently no-op.
         */
        SettingsPatch: {
            /** Hosts */
            hosts?: {
                [key: string]: components["schemas"]["HostSettingsPatch"];
            } | null;
            /** Max Concurrent */
            max_concurrent?: number | null;
            /** Require Source */
            require_source?: boolean | null;
            /** Pool Caps */
            pool_caps?: {
                [key: string]: number;
            } | null;
            state_reconciliation?: components["schemas"]["StateReconciliationPatch"] | null;
            orphan_gc?: components["schemas"]["OrphanGCPatch"] | null;
            host_autotune?: components["schemas"]["HostAutotunePatch"] | null;
            notify?: components["schemas"]["NotifyPatch"] | null;
            archive?: components["schemas"]["ArchivePatch"] | null;
        };
        /** StateOut */
        StateOut: {
            /** Self Host */
            self_host: string;
            settings: components["schemas"]["Settings"];
            /** Running Total */
            running_total: number;
            /** Running Per Host */
            running_per_host: {
                [key: string]: number;
            };
            /** Running Per Pool */
            running_per_pool?: {
                [key: string]: number;
            };
            /** Jobs */
            jobs: components["schemas"]["JobSummaryOut"][];
        };
        /** StateReconciliationPatch */
        StateReconciliationPatch: {
            /** Max Concurrent Probes */
            max_concurrent_probes?: number | null;
            /** Seconds Between Probes */
            seconds_between_probes?: number | null;
        };
        /**
         * StateReconciliationSettings
         * @description Resolver knobs (periodic unknown/ghosted sweep).
         */
        StateReconciliationSettings: {
            /**
             * Max Concurrent Probes
             * @default 16
             */
            max_concurrent_probes: number;
            /**
             * Seconds Between Probes
             * @default 30
             */
            seconds_between_probes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
        };
    };
    monitor_stream_api_monitor_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                full?: boolean;
                arena?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_arenas_api_arenas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArenaSummaryOut"][];
                };
            };
        };
    };
    get_arena_api_arenas__arena__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArenaDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arena_pause_api_arenas__arena__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arena_resume_api_arenas__arena__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arena_reclaim_api_arenas__arena__reclaim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arena: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arena_cancel_api_arenas__arena__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arena: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclaim_job_api_jobs__job_id__reclaim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclaim_instance_api_jobs__job_id__instances__instance_id__reclaim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_done_err_api_jobs__job_id__retry_done_err_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RetryDoneErrRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_job_ep_api_jobs__job_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_job_ep_api_jobs__job_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filter_presets_api_filter_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_filter_presets_api_filter_presets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
